services:
  app:
    build: .
    container_name: discord-gaming-bot
    command: python src/bot.py
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - CHANNEL_ID=${CHANNEL_ID}
      - GUILD_ID=${GUILD_ID}
      - EPIC_GAMES_API=${EPIC_GAMES_API}
      - RSA_KEY_PATH=${RSA_KEY_PATH}
      - INSTANCE_ID=${INSTANCE_ID}
      - STEAMSPY_API=${STEAMSPY_API}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
